server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  devtools:
    livereload:
      enabled: false
